name: chase_metrics
description: Prometheus-style metrics plugin for Chase framework.
version: 0.0.1
repository: https://github.com/arihas26/chase/tree/main/packages/chase_metrics
publish_to: none  # Remove when ready to publish

environment:
  sdk: ^3.8.0

dependencies:
  chase:
    path: ../../

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
